#  This file contains a description of the items in the data-raw
#
#  0- All data files are placed in the Additional Data folder except KEGGPATHS.
#
#  1- AdditionalData/pathwaysData and  AdditionalData/pathwayDataNames are
#     the outputs generated by the code in the PathwaySelectionScript.R
#     these files are later used in generating the background data for CADIA.
#     In the case of future updates this code would prove useful and essential.
#     The file  AdditionalData/pathlist.csv contains
#     the names of the all the files in the KEGGPATHS folder.
#
#
#  2- The files  AdditionalData/GoodPathways and  AdditionalData/BadPathways are
#     outputs of quality check and preprocessing step, detailed in the selection
#     process and the paper. BadPathways are excluded from the analysis.
#
#
#  3- The files  AdditionalData/err_ssc,  AdditionalData/err_ora, and
#     AdditionalData/err_cdist are from synthetic data
#     processing step. The accompanying code is in the
#     TestCodes/04-RandomSampling.R
#
#  4- The file  AdditionalData/allGeneNames is simply all gene names in the
#     HG-U133b platform, after cleaning.
#
#  5- The folder  AdditionalData/EnrichNetResults contains the runs of Enrichnet
#     as described inthe original manuscript.
#
#  6- In the folder of TestCodes/ : The files 01_, 02_, and 03_ contain the
#     complete analysis of all test cases using all of the models in the paper.
#     The files 04_, and 05_ are for the synthetic data testing. 00_ is plots.
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
